DECLARE v_count INTEGER := 0;  

BEGIN 
 
  SELECT
    COUNT (1)
  INTO
    v_count
  FROM
    dba_users
  WHERE
    username = UPPER ('CALENDAR'); 
  IF v_count != 0
  THEN
    EXECUTE IMMEDIATE ('DROP USER CALENDAR CASCADE'); 
  END IF; 
 
EXECUTE IMMEDIATE ('CREATE USER CALENDAR IDENTIFIED BY password
  DEFAULT TABLESPACE "USERS"
  TEMPORARY TABLESPACE "TEMP"');

  
EXECUTE IMMEDIATE('GRANT USERS TO CALENDAR'); // ABPXE_USERS Tricast gépeken, mindenhol máshol USERS
    
EXECUTE IMMEDIATE('GRANT ALL PRIVILEGES TO CALENDAR'); 
  
EXECUTE IMMEDIATE ('
CREATE TABLE "CALENDAR"."ACCOUNTS" 
   (	
   "ID" NUMBER(18,0) NOT NULL ENABLE, 
   "USERNAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
   "PASSWORD" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
   "REALNAME" VARCHAR2(120 BYTE) NOT NULL ENABLE, 
   "DAYSOFFPERYEAR" NUMBER(18,0) NOT NULL ENABLE, 
   "SICKLEAVEPERYEAR" NUMBER(18,0), 
	CONSTRAINT "ACCOUNTS_PK" PRIMARY KEY ("ID"), 
	CONSTRAINT "SICKNOTNULL" CHECK ("SICKLEAVEPERYEAR" IS NOT NULL) ENABLE
   ) TABLESPACE "USERS"
');

EXECUTE IMMEDIATE ('
CREATE SEQUENCE "CALENDAR"."SEQ_ACCOUNTS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
');

EXECUTE IMMEDIATE ('
  CREATE TABLE "CALENDAR"."BLOCKEDDAYS" 
   (	
    "ID" NUMBER(18,0) NOT NULL ENABLE, 
	"DAY" VARCHAR2(8 CHAR)
   ) 
   TABLESPACE "USERS"
');

EXECUTE IMMEDIATE ('   
   CREATE SEQUENCE  "CALENDAR"."SEQ_BLOCKEDDAYS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
');

EXECUTE IMMEDIATE ('
  CREATE TABLE "CALENDAR"."HOLIDAYS" 
   (	
    "ID" NUMBER(18,0) NOT NULL ENABLE, 
	"ACCOUNTID" NUMBER(18,0), 
	"FROMDAY" VARCHAR2(8 CHAR) NOT NULL ENABLE, 
	"TODAY" VARCHAR2(8 CHAR) NOT NULL ENABLE, 
	"TYPE" NUMBER(18,0) NOT NULL ENABLE, 
	"ACTUALDAYCOUNT" NUMBER(18,0), 
	 CONSTRAINT "HOLIDAYS_ACCOUNTS_FK1" FOREIGN KEY ("ACCOUNTID")
	 REFERENCES "CALENDAR"."ACCOUNTS" ("ID") ENABLE
   ) 
  TABLESPACE "USERS"
'); 

EXECUTE IMMEDIATE ('
  CREATE SEQUENCE  "CALENDAR"."SEQ_HOLIDAYS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
');

END;
   